package code

var enUSText = map[int]string{
	ServerError:        "Internal server error",
	TooManyRequests:    "Too many requests",
	ParamBindError:     "Parameter error",
	AuthorizationError: "Authorization error",
	UrlSignError:       "URL signature error",
	CacheSetError:      "Failed to set cache",
	CacheGetError:      "Failed to get cache",
	CacheDelError:      "Failed to del cache",
	CacheNotExist:      "Cache does not exist",
	ResubmitError:      "Please do not submit repeatedly",
	HashIdsEncodeError: "HashID encryption failed",
	HashIdsDecodeError: "HashID decryption failed",
	RBACError:          "No access",
	RedisConnectError:  "Failed to connection Redis",
	MySQLConnectError:  "Failed to connection MySQL",
	WriteConfigError:   "Failed to write configuration file",
	SendEmailError:     "Failed to send mail",
	MySQLExecError:     "SQL execution failed",
	GoVersionError:     "Go Version mismatch",
	SocketConnectError: "Socket not connected",
	SocketSendError:    "Socket message sending failed",

	UserResetPasswordError:      "Reset password failed",
	UserLoginError:              "Login failed",
	UserSignupError:             "Sign up failed",
	UserLogOutError:             "Exit failed",
	UserModifyPasswordError:     "Failed to modify password",
	UserOldPasswordError:        "Failed to get Useristrator menu authorization list",
	UserModifyPersonalInfoError: "Failed to modify personal information",
	UserDetailError:             "Failed to get personal information",

	PrizeCreateError: "Failed to create Useristrator",
	PrizeListError:   "Failed to get Useristrator list",
	PrizeDeleteError: "Failed to delete Useristrator",
	PrizeUpdateError: "Failed to update Useristrator",
	PrizeDetailError: "Failed to get personal information",
}
