package code

var zhCNText = map[int]string{
	ServerError:        "内部服务器错误",
	TooManyRequests:    "请求过多",
	ParamBindError:     "参数信息错误",
	AuthorizationError: "签名信息错误",
	UrlSignError:       "参数签名错误",
	CacheSetError:      "设置缓存失败",
	CacheGetError:      "获取缓存失败",
	CacheDelError:      "删除缓存失败",
	CacheNotExist:      "缓存不存在",
	ResubmitError:      "请勿重复提交",
	HashIdsEncodeError: "HashID 加密失败",
	HashIdsDecodeError: "HashID 解密失败",
	RBACError:          "暂无访问权限",
	RedisConnectError:  "Redis 连接失败",
	MySQLConnectError:  "MySQL 连接失败",
	WriteConfigError:   "写入配置文件失败",
	SendEmailError:     "发送邮件失败",
	MySQLExecError:     "SQL 执行失败",
	GoVersionError:     "Go 版本不满足要求",
	SocketConnectError: "Socket 未连接",
	SocketSendError:    "Socket 消息发送失败",

	UserResetPasswordError:      "重置密码失败",
	UserLoginError:              "登录失败",
	UserSignupError:             "注册失败",
	UserLogOutError:             "退出失败",
	UserModifyPasswordError:     "修改密码失败",
	UserOldPasswordError:        "修改密码失败，旧密码错误",
	UserModifyPersonalInfoError: "修改个人信息失败",
	UserDetailError:             "获取个人信息失败",

	PrizeCreateError: "新增奖品失败",
	PrizeListError:   "获取奖品列表失败",
	PrizeDeleteError: "删除奖品失败",
	PrizeUpdateError: "更新奖品失败",
	PrizeDetailError: "获取奖品信息失败",

	CaptchaGenerateError: "生成验证码图片失败",
}
